index:
    path: /
    controller: App\Controller\DefaultController::index



## Joke Routes

api.joke.get:
    path: /joke/{jokeId}
    controller: App\Controller\JokeController::getById
    methods:  GET
    requirements:
        jokeId:  '\d+'

api.joke.delete:
    path: /joke/{jokeId}
    controller: App\Controller\JokeController::deleteById
    methods:  DELETE
    requirements:
        jokeId:  '\d+'

api.joke.put:
    path: /joke/{jokeId}
    controller: App\Controller\JokeController::updateById
    methods:  PUT
    requirements:
        jokeId:  '\d+'

api.joke.post:
    path: /joke
    controller: App\Controller\JokeController::add
    methods:  POST

api.joke.getRandom:
    path: /joke
    controller: App\Controller\JokeController::getRandom
    methods:  GET