index:
    path: /
    controller: App\Controller\DefaultController::index

# config/routes.yaml
app.swagger_ui:
    path: /doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }


## Joke Routes

api.joke.get:
    path: /joke/{jokeId}
    controller: App\Controller\JokeController::getById
    methods:  GET
    requirements:
        jokeId:  '\d+'

api.joke.delete:
    path: /joke/{jokeId}
    controller: App\Controller\JokeController::deleteById
    methods:  DELETE
    requirements:
        jokeId:  '\d+'

api.joke.put:
    path: /joke/{jokeId}
    controller: App\Controller\JokeController::updateById
    methods:  PUT
    requirements:
        jokeId:  '\d+'

api.joke.getRandom:
    path: /joke/random
    controller: App\Controller\JokeController::getRandom
    methods:  GET

api.joke.post:
    path: /joke
    controller: App\Controller\JokeController::add
    methods:  POST

api.joke.getCollection:
    path: /jokes
    controller: App\Controller\JokeController::getCollection
    methods:  GET